upgrade

diff --git a/srcs/requirements/wordpress/Dockerfile b/srcs/requirements/wordpress/Dockerfile
--- a/srcs/requirements/wordpress/Dockerfile
+++ b/srcs/requirements/wordpress/Dockerfile
@@ -1,8 +1,5 @@
 FROM php:8.1-fpm-alpine
 
-LABEL version="0.2"
-LABEL description="Wordpress and php"
-
 # persistent dependencies
 RUN set -eux; \
 	apk add --no-cache \
@@ -14,15 +11,125 @@ RUN set -eux; \
 	imagemagick \
 	;
 
-# # Crear un directorio para almacenar los datos de WordPress
-# RUN mkdir -p /var/www/html
+# install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
+RUN set -ex; \
+	\
+	apk add --no-cache --virtual .build-deps \
+	$PHPIZE_DEPS \
+	freetype-dev \
+	icu-dev \
+	imagemagick-dev \
+	libjpeg-turbo-dev \
+	libpng-dev \
+	libwebp-dev \
+	libzip-dev \
+	; \
+	\
+	docker-php-ext-configure gd \
+	--with-freetype \
+	--with-jpeg \
+	--with-webp \
+	; \
+	docker-php-ext-install -j "$(nproc)" \
+	bcmath \
+	exif \
+	gd \
+	intl \
+	mysqli \
+	zip \
+	; \
+	# WARNING: imagick is likely not supported on Alpine: https://github.com/Imagick/imagick/issues/328
+	# https://pecl.php.net/package/imagick
+	pecl install imagick-3.6.0; \
+	docker-php-ext-enable imagick; \
+	rm -r /tmp/pear; \
+	\
+	# some misbehaving extensions end up outputting to stdout 🙈 (https://github.com/docker-library/wordpress/issues/669#issuecomment-993945967)
+	out="$(php -r 'exit(0);')"; \
+	[ -z "$out" ]; \
+	err="$(php -r 'exit(0);' 3>&1 1>&2 2>&3)"; \
+	[ -z "$err" ]; \
+	\
+	extDir="$(php -r 'echo ini_get("extension_dir");')"; \
+	[ -d "$extDir" ]; \
+	runDeps="$( \
+	scanelf --needed --nobanner --format '%n#p' --recursive "$extDir" \
+	| tr ',' '\n' \
+	| sort -u \
+	| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
+	)"; \
+	apk add --no-network --virtual .wordpress-phpexts-rundeps $runDeps; \
+	apk del --no-network .build-deps; \
+	\
+	! { ldd "$extDir"/*.so | grep 'not found'; }; \
+	# check for output like "PHP Warning:  PHP Startup: Unable to load dynamic library 'foo' (tried: ...)
+	err="$(php --version 3>&1 1>&2 2>&3)"; \
+	[ -z "$err" ]
 
-# # Copiar WordPress al directorio de trabajo
-# COPY wordpress /var/www/html
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+	docker-php-ext-enable opcache; \
+	{ \
+	echo 'opcache.memory_consumption=128'; \
+	echo 'opcache.interned_strings_buffer=8'; \
+	echo 'opcache.max_accelerated_files=4000'; \
+	echo 'opcache.revalidate_freq=2'; \
+	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+	# https://www.php.net/manual/en/errorfunc.constants.php
+	# https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+	echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+	echo 'display_errors = Off'; \
+	echo 'display_startup_errors = Off'; \
+	echo 'log_errors = On'; \
+	echo 'error_log = /dev/stderr'; \
+	echo 'log_errors_max_len = 1024'; \
+	echo 'ignore_repeated_errors = On'; \
+	echo 'ignore_repeated_source = Off'; \
+	echo 'html_errors = Off'; \
+	} > /usr/local/etc/php/conf.d/error-logging.ini
 
-WORKDIR /var/www/html
-# Establecer permisos adecuados
-RUN chown -R nobody:nogroup .
+# RUN set -eux; \
+# 	version='6.4.3'; \
+# 	sha1='ee3bc3a73ab3cfa535c46f111eb641b3467fa44e'; \
+# 	\
+# 	curl -o wordpress.tar.gz -fL "https://wordpress.org/wordpress-$version.tar.gz"; \
+# 	echo "$sha1 *wordpress.tar.gz" | sha1sum -c -; \
+# 	\
+# 	# upstream tarballs include ./wordpress/ so this gives us /var/www/wp
+# 	tar -xzf wordpress.tar.gz -C /usr/src/; \
+# 	rm wordpress.tar.gz; \
+# 	\
+# 	# https://wordpress.org/support/article/htaccess/
+# 	[ ! -e /var/www/wp/.htaccess ]; \
+# 	{ \
+# 	echo '# BEGIN WordPress'; \
+# 	echo ''; \
+# 	echo 'RewriteEngine On'; \
+# 	echo 'RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]'; \
+# 	echo 'RewriteBase /'; \
+# 	echo 'RewriteRule ^index\.php$ - [L]'; \
+# 	echo 'RewriteCond %{REQUEST_FILENAME} !-f'; \
+# 	echo 'RewriteCond %{REQUEST_FILENAME} !-d'; \
+# 	echo 'RewriteRule . /index.php [L]'; \
+# 	echo ''; \
+# 	echo '# END WordPress'; \
+# 	} > /var/www/wp/.htaccess; \
+# 	\
+# 	# pre-create wp-content (and single-level children) for folks who want to bind-mount themes, etc so permissions are pre-created properly instead of root:root
+# 	# wp-content/cache: https://github.com/docker-library/wordpress/issues/534#issuecomment-705733507
+# 	mkdir wp-content; \
+# 	for dir in /var/www/wp/wp-content/*/ cache; do \
+# 	dir="$(basename "${dir%/}")"; \
+# 	mkdir "wp-content/$dir"; \
+# 	done; \
+
+WORKDIR /var/www/wp
+
+# RUN	chown -R www-data:www-data . \
+# 	chmod -R 1777 .
 
 # Exponer el puerto 9000 para PHP-FPM
 EXPOSE 9000
